//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.Isida4_webservice_main")]
    public interface Isida4_webservice_main
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sida4_webservice_mainIntf-Isida4_webservice_main#rrr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.rrrResponse> rrrAsync(ServiceReference1.rrrRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sida4_webservice_mainIntf-Isida4_webservice_main#GetCertificateId_sahem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.GetCertificateId_sahemResponse> GetCertificateId_sahemAsync(ServiceReference1.GetCertificateId_sahemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sida4_webservice_mainIntf-Isida4_webservice_main#ExecProcInOut1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.ExecProcInOut1Response> ExecProcInOut1Async(ServiceReference1.ExecProcInOut1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sida4_webservice_mainIntf-Isida4_webservice_main#ExecProc4Select", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.ExecProc4SelectResponse> ExecProc4SelectAsync(ServiceReference1.ExecProc4SelectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sida4_webservice_mainIntf-Isida4_webservice_main#GetP_sida", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.GetP_sidaResponse> GetP_sidaAsync(ServiceReference1.GetP_sidaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sida4_webservice_mainIntf-Isida4_webservice_main#Fnsend_sms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.Fnsend_smsResponse> Fnsend_smsAsync(ServiceReference1.Fnsend_smsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sida4_webservice_mainIntf-Isida4_webservice_main#getip_vahed_digit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.getip_vahed_digitResponse> getip_vahed_digitAsync(ServiceReference1.getip_vahed_digitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sida4_webservice_mainIntf-Isida4_webservice_main#get_proc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.get_procResponse> get_procAsync(ServiceReference1.get_procRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sida4_webservice_mainIntf-Isida4_webservice_main#rrr_new", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.rrr_newResponse> rrr_newAsync(ServiceReference1.rrr_newRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sida4_webservice_mainIntf-Isida4_webservice_main#shenas_bank", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.shenas_bankResponse> shenas_bankAsync(ServiceReference1.shenas_bankRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sida4_webservice_mainIntf-Isida4_webservice_main#send_data_to_gra", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.send_data_to_graResponse> send_data_to_graAsync(ServiceReference1.send_data_to_graRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sida4_webservice_mainIntf-Isida4_webservice_main#send_data_to_ican", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.send_data_to_icanResponse> send_data_to_icanAsync(ServiceReference1.send_data_to_icanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sida4_webservice_mainIntf-Isida4_webservice_main#send_attach_to_ican", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.send_attach_to_icanResponse> send_attach_to_icanAsync(ServiceReference1.send_attach_to_icanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sida4_webservice_mainIntf-Isida4_webservice_main#sendsmsgroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.sendsmsgroupResponse> sendsmsgroupAsync(ServiceReference1.sendsmsgroupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sida4_webservice_mainIntf-Isida4_webservice_main#mobile_login_main", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.mobile_login_mainResponse> mobile_login_mainAsync(ServiceReference1.mobile_login_mainRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sida4_webservice_mainIntf-Isida4_webservice_main#ctrl_p", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.ctrl_pResponse> ctrl_pAsync(ServiceReference1.ctrl_pRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sida4_webservice_mainIntf-Isida4_webservice_main#Inquiry_from_u", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.Inquiry_from_uResponse> Inquiry_from_uAsync(ServiceReference1.Inquiry_from_uRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sida4_webservice_mainIntf-Isida4_webservice_main#InitKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.InitKeyResponse> InitKeyAsync(ServiceReference1.InitKeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sida4_webservice_mainIntf-Isida4_webservice_main#DecryptPrimarykey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.DecryptPrimarykeyResponse> DecryptPrimarykeyAsync(ServiceReference1.DecryptPrimarykeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sida4_webservice_mainIntf-Isida4_webservice_main#ctrl_elec", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.ctrl_elecResponse> ctrl_elecAsync(ServiceReference1.ctrl_elecRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sida4_webservice_mainIntf-Isida4_webservice_main#ctrl_change_data_sign", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.ctrl_change_data_signResponse> ctrl_change_data_signAsync(ServiceReference1.ctrl_change_data_signRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sida4_webservice_mainIntf-Isida4_webservice_main#update_data_sign", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.update_data_signResponse> update_data_signAsync(ServiceReference1.update_data_signRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rrr", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class rrrRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string var1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string var2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string var3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string var4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string var5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string var6;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string var7;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string var8;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string var9;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public string var10;
        
        public rrrRequest()
        {
        }
        
        public rrrRequest(string var1, string var2, string var3, string var4, string var5, string var6, string var7, string var8, string var9, string var10)
        {
            this.var1 = var1;
            this.var2 = var2;
            this.var3 = var3;
            this.var4 = var4;
            this.var5 = var5;
            this.var6 = var6;
            this.var7 = var7;
            this.var8 = var8;
            this.var9 = var9;
            this.var10 = var10;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rrrResponse", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class rrrResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string var1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string var2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string var3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string var4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string var5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string var6;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string var7;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string var8;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string var9;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public string var10;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=10)]
        public string @return;
        
        public rrrResponse()
        {
        }
        
        public rrrResponse(string var1, string var2, string var3, string var4, string var5, string var6, string var7, string var8, string var9, string var10, string @return)
        {
            this.var1 = var1;
            this.var2 = var2;
            this.var3 = var3;
            this.var4 = var4;
            this.var5 = var5;
            this.var6 = var6;
            this.var7 = var7;
            this.var8 = var8;
            this.var9 = var9;
            this.var10 = var10;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCertificateId_sahem", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class GetCertificateId_sahemRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string date_;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string time_;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string type_s;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string param;
        
        public GetCertificateId_sahemRequest()
        {
        }
        
        public GetCertificateId_sahemRequest(string code, string date_, string time_, string type_s, string param)
        {
            this.code = code;
            this.date_ = date_;
            this.time_ = time_;
            this.type_s = type_s;
            this.param = param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCertificateId_sahemResponse", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class GetCertificateId_sahemResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string date_;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string time_;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string type_s;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string param;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string @return;
        
        public GetCertificateId_sahemResponse()
        {
        }
        
        public GetCertificateId_sahemResponse(string code, string date_, string time_, string type_s, string param, string @return)
        {
            this.code = code;
            this.date_ = date_;
            this.time_ = time_;
            this.type_s = type_s;
            this.param = param;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecProcInOut1", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class ExecProcInOut1Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string procname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string paramInCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string paramOutCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string param1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string param2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string param3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string param4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string param5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string param6;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public string param7;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=10)]
        public string param8;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=11)]
        public string param9;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=12)]
        public string param10;
        
        public ExecProcInOut1Request()
        {
        }
        
        public ExecProcInOut1Request(string procname, string paramInCount, string paramOutCount, string param1, string param2, string param3, string param4, string param5, string param6, string param7, string param8, string param9, string param10)
        {
            this.procname = procname;
            this.paramInCount = paramInCount;
            this.paramOutCount = paramOutCount;
            this.param1 = param1;
            this.param2 = param2;
            this.param3 = param3;
            this.param4 = param4;
            this.param5 = param5;
            this.param6 = param6;
            this.param7 = param7;
            this.param8 = param8;
            this.param9 = param9;
            this.param10 = param10;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecProcInOut1Response", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class ExecProcInOut1Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public ExecProcInOut1Response()
        {
        }
        
        public ExecProcInOut1Response(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecProc4Select", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class ExecProc4SelectRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string procname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string proccount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string param1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string param2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string param3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string param4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string param5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string param6;
        
        public ExecProc4SelectRequest()
        {
        }
        
        public ExecProc4SelectRequest(string procname, string proccount, string param1, string param2, string param3, string param4, string param5, string param6)
        {
            this.procname = procname;
            this.proccount = proccount;
            this.param1 = param1;
            this.param2 = param2;
            this.param3 = param3;
            this.param4 = param4;
            this.param5 = param5;
            this.param6 = param6;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecProc4SelectResponse", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class ExecProc4SelectResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public ExecProc4SelectResponse()
        {
        }
        
        public ExecProc4SelectResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetP_sida", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class GetP_sidaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string newPacket;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string ctrl;
        
        public GetP_sidaRequest()
        {
        }
        
        public GetP_sidaRequest(string newPacket, string ctrl)
        {
            this.newPacket = newPacket;
            this.ctrl = ctrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetP_sidaResponse", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class GetP_sidaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string ctrl;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string @return;
        
        public GetP_sidaResponse()
        {
        }
        
        public GetP_sidaResponse(string ctrl, string @return)
        {
            this.ctrl = ctrl;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Fnsend_sms", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class Fnsend_smsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string param;
        
        public Fnsend_smsRequest()
        {
        }
        
        public Fnsend_smsRequest(string param)
        {
            this.param = param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Fnsend_smsResponse", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class Fnsend_smsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string param;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int @return;
        
        public Fnsend_smsResponse()
        {
        }
        
        public Fnsend_smsResponse(string param, int @return)
        {
            this.param = param;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getip_vahed_digit", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class getip_vahed_digitRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string param1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string param2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string param3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string type_s;
        
        public getip_vahed_digitRequest()
        {
        }
        
        public getip_vahed_digitRequest(string param1, string param2, string param3, string type_s)
        {
            this.param1 = param1;
            this.param2 = param2;
            this.param3 = param3;
            this.type_s = type_s;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getip_vahed_digitResponse", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class getip_vahed_digitResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public getip_vahed_digitResponse()
        {
        }
        
        public getip_vahed_digitResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_proc", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class get_procRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string param;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string param_dif;
        
        public get_procRequest()
        {
        }
        
        public get_procRequest(string param, string param_dif)
        {
            this.param = param;
            this.param_dif = param_dif;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_procResponse", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class get_procResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string param;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string param_dif;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string @return;
        
        public get_procResponse()
        {
        }
        
        public get_procResponse(string param, string param_dif, string @return)
        {
            this.param = param;
            this.param_dif = param_dif;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rrr_new", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class rrr_newRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string var1;
        
        public rrr_newRequest()
        {
        }
        
        public rrr_newRequest(string var1)
        {
            this.var1 = var1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rrr_newResponse", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class rrr_newResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string var1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string @return;
        
        public rrr_newResponse()
        {
        }
        
        public rrr_newResponse(string var1, string @return)
        {
            this.var1 = var1;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="shenas_bank", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class shenas_bankRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string shenas;
        
        public shenas_bankRequest()
        {
        }
        
        public shenas_bankRequest(string shenas)
        {
            this.shenas = shenas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="shenas_bankResponse", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class shenas_bankResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public shenas_bankResponse()
        {
        }
        
        public shenas_bankResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="send_data_to_gra", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class send_data_to_graRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string param1;
        
        public send_data_to_graRequest()
        {
        }
        
        public send_data_to_graRequest(string param1)
        {
            this.param1 = param1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="send_data_to_graResponse", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class send_data_to_graResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string param1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string @return;
        
        public send_data_to_graResponse()
        {
        }
        
        public send_data_to_graResponse(string param1, string @return)
        {
            this.param1 = param1;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="send_data_to_ican", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class send_data_to_icanRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string param1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string param2;
        
        public send_data_to_icanRequest()
        {
        }
        
        public send_data_to_icanRequest(string param1, string param2)
        {
            this.param1 = param1;
            this.param2 = param2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="send_data_to_icanResponse", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class send_data_to_icanResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string param1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string param2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string @return;
        
        public send_data_to_icanResponse()
        {
        }
        
        public send_data_to_icanResponse(string param1, string param2, string @return)
        {
            this.param1 = param1;
            this.param2 = param2;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="send_attach_to_ican", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class send_attach_to_icanRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string pic;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string MainEC;
        
        public send_attach_to_icanRequest()
        {
        }
        
        public send_attach_to_icanRequest(string pic, string MainEC)
        {
            this.pic = pic;
            this.MainEC = MainEC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="send_attach_to_icanResponse", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class send_attach_to_icanResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string MainEC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string @return;
        
        public send_attach_to_icanResponse()
        {
        }
        
        public send_attach_to_icanResponse(string MainEC, string @return)
        {
            this.MainEC = MainEC;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendsmsgroup", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class sendsmsgroupRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string param;
        
        public sendsmsgroupRequest()
        {
        }
        
        public sendsmsgroupRequest(string param)
        {
            this.param = param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendsmsgroupResponse", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class sendsmsgroupResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string param;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int @return;
        
        public sendsmsgroupResponse()
        {
        }
        
        public sendsmsgroupResponse(string param, int @return)
        {
            this.param = param;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mobile_login_main", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class mobile_login_mainRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string deviceId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string param1;
        
        public mobile_login_mainRequest()
        {
        }
        
        public mobile_login_mainRequest(string deviceId, string param1)
        {
            this.deviceId = deviceId;
            this.param1 = param1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mobile_login_mainResponse", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class mobile_login_mainResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public mobile_login_mainResponse()
        {
        }
        
        public mobile_login_mainResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ctrl_p", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class ctrl_pRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string param1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string param2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string param3;
        
        public ctrl_pRequest()
        {
        }
        
        public ctrl_pRequest(string param1, string param2, string param3)
        {
            this.param1 = param1;
            this.param2 = param2;
            this.param3 = param3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ctrl_pResponse", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class ctrl_pResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string param1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string param2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string param3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string @return;
        
        public ctrl_pResponse()
        {
        }
        
        public ctrl_pResponse(string param1, string param2, string param3, string @return)
        {
            this.param1 = param1;
            this.param2 = param2;
            this.param3 = param3;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Inquiry_from_u", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class Inquiry_from_uRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string param1;
        
        public Inquiry_from_uRequest()
        {
        }
        
        public Inquiry_from_uRequest(string param1)
        {
            this.param1 = param1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Inquiry_from_uResponse", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class Inquiry_from_uResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string param1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string @return;
        
        public Inquiry_from_uResponse()
        {
        }
        
        public Inquiry_from_uResponse(string param1, string @return)
        {
            this.param1 = param1;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InitKey", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class InitKeyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string deviceId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string pk;
        
        public InitKeyRequest()
        {
        }
        
        public InitKeyRequest(string deviceId, string pk)
        {
            this.deviceId = deviceId;
            this.pk = pk;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InitKeyResponse", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class InitKeyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public InitKeyResponse()
        {
        }
        
        public InitKeyResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DecryptPrimarykey", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class DecryptPrimarykeyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string deviceId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string privateKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string primaryKeyEncrypted;
        
        public DecryptPrimarykeyRequest()
        {
        }
        
        public DecryptPrimarykeyRequest(string deviceId, string privateKey, string primaryKeyEncrypted)
        {
            this.deviceId = deviceId;
            this.privateKey = privateKey;
            this.primaryKeyEncrypted = primaryKeyEncrypted;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DecryptPrimarykeyResponse", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class DecryptPrimarykeyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public DecryptPrimarykeyResponse()
        {
        }
        
        public DecryptPrimarykeyResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ctrl_elec", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class ctrl_elecRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string param1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string param2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string param3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string param4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string param5;
        
        public ctrl_elecRequest()
        {
        }
        
        public ctrl_elecRequest(string param1, string param2, string param3, string param4, string param5)
        {
            this.param1 = param1;
            this.param2 = param2;
            this.param3 = param3;
            this.param4 = param4;
            this.param5 = param5;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ctrl_elecResponse", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class ctrl_elecResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public ctrl_elecResponse()
        {
        }
        
        public ctrl_elecResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ctrl_change_data_sign", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class ctrl_change_data_signRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string param1;
        
        public ctrl_change_data_signRequest()
        {
        }
        
        public ctrl_change_data_signRequest(string param1)
        {
            this.param1 = param1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ctrl_change_data_signResponse", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class ctrl_change_data_signResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public ctrl_change_data_signResponse()
        {
        }
        
        public ctrl_change_data_signResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="update_data_sign", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class update_data_signRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string param1;
        
        public update_data_signRequest()
        {
        }
        
        public update_data_signRequest(string param1)
        {
            this.param1 = param1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="update_data_signResponse", WrapperNamespace="urn:sida4_webservice_mainIntf-Isida4_webservice_main", IsWrapped=true)]
    public partial class update_data_signResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public update_data_signResponse()
        {
        }
        
        public update_data_signResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    public interface Isida4_webservice_mainChannel : ServiceReference1.Isida4_webservice_main, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    public partial class Isida4_webservice_mainClient : System.ServiceModel.ClientBase<ServiceReference1.Isida4_webservice_main>, ServiceReference1.Isida4_webservice_main
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Isida4_webservice_mainClient() : 
                base(Isida4_webservice_mainClient.GetDefaultBinding(), Isida4_webservice_mainClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.Isida4_webservice_mainPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Isida4_webservice_mainClient(EndpointConfiguration endpointConfiguration) : 
                base(Isida4_webservice_mainClient.GetBindingForEndpoint(endpointConfiguration), Isida4_webservice_mainClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Isida4_webservice_mainClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Isida4_webservice_mainClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Isida4_webservice_mainClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Isida4_webservice_mainClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Isida4_webservice_mainClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.rrrResponse> rrrAsync(ServiceReference1.rrrRequest request)
        {
            return base.Channel.rrrAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetCertificateId_sahemResponse> GetCertificateId_sahemAsync(ServiceReference1.GetCertificateId_sahemRequest request)
        {
            return base.Channel.GetCertificateId_sahemAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ExecProcInOut1Response> ExecProcInOut1Async(ServiceReference1.ExecProcInOut1Request request)
        {
            return base.Channel.ExecProcInOut1Async(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ExecProc4SelectResponse> ExecProc4SelectAsync(ServiceReference1.ExecProc4SelectRequest request)
        {
            return base.Channel.ExecProc4SelectAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetP_sidaResponse> GetP_sidaAsync(ServiceReference1.GetP_sidaRequest request)
        {
            return base.Channel.GetP_sidaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Fnsend_smsResponse> Fnsend_smsAsync(ServiceReference1.Fnsend_smsRequest request)
        {
            return base.Channel.Fnsend_smsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getip_vahed_digitResponse> getip_vahed_digitAsync(ServiceReference1.getip_vahed_digitRequest request)
        {
            return base.Channel.getip_vahed_digitAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.get_procResponse> get_procAsync(ServiceReference1.get_procRequest request)
        {
            return base.Channel.get_procAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.rrr_newResponse> rrr_newAsync(ServiceReference1.rrr_newRequest request)
        {
            return base.Channel.rrr_newAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.shenas_bankResponse> shenas_bankAsync(ServiceReference1.shenas_bankRequest request)
        {
            return base.Channel.shenas_bankAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.send_data_to_graResponse> send_data_to_graAsync(ServiceReference1.send_data_to_graRequest request)
        {
            return base.Channel.send_data_to_graAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.send_data_to_icanResponse> send_data_to_icanAsync(ServiceReference1.send_data_to_icanRequest request)
        {
            return base.Channel.send_data_to_icanAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.send_attach_to_icanResponse> send_attach_to_icanAsync(ServiceReference1.send_attach_to_icanRequest request)
        {
            return base.Channel.send_attach_to_icanAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.sendsmsgroupResponse> sendsmsgroupAsync(ServiceReference1.sendsmsgroupRequest request)
        {
            return base.Channel.sendsmsgroupAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.mobile_login_mainResponse> mobile_login_mainAsync(ServiceReference1.mobile_login_mainRequest request)
        {
            return base.Channel.mobile_login_mainAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ctrl_pResponse> ctrl_pAsync(ServiceReference1.ctrl_pRequest request)
        {
            return base.Channel.ctrl_pAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Inquiry_from_uResponse> Inquiry_from_uAsync(ServiceReference1.Inquiry_from_uRequest request)
        {
            return base.Channel.Inquiry_from_uAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.InitKeyResponse> InitKeyAsync(ServiceReference1.InitKeyRequest request)
        {
            return base.Channel.InitKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.DecryptPrimarykeyResponse> DecryptPrimarykeyAsync(ServiceReference1.DecryptPrimarykeyRequest request)
        {
            return base.Channel.DecryptPrimarykeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ctrl_elecResponse> ctrl_elecAsync(ServiceReference1.ctrl_elecRequest request)
        {
            return base.Channel.ctrl_elecAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ctrl_change_data_signResponse> ctrl_change_data_signAsync(ServiceReference1.ctrl_change_data_signRequest request)
        {
            return base.Channel.ctrl_change_data_signAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.update_data_signResponse> update_data_signAsync(ServiceReference1.update_data_signRequest request)
        {
            return base.Channel.update_data_signAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Isida4_webservice_mainPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Isida4_webservice_mainPort))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.1.18:8888/soap/Isida4_webservice_main");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Isida4_webservice_mainClient.GetBindingForEndpoint(EndpointConfiguration.Isida4_webservice_mainPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Isida4_webservice_mainClient.GetEndpointAddress(EndpointConfiguration.Isida4_webservice_mainPort);
        }
        
        public enum EndpointConfiguration
        {
            
            Isida4_webservice_mainPort,
        }
    }
}
